# Book settings
title:
author: Cátedra de Fundamentos de la Ciencia de Datos
logo: docs/images/unr_logo.png
only_build_toc_files: false

repository:
  url: https://github.com/msoltadeo/fdcd
  branch: main

# Execution Settings
execute:
  execute_notebooks: off

# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"